export const LOADING = "LOADING";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";

export const SET_FILMS_LIST = "SET_FILMS_LIST";
export const SET_POSTERS = "SET_POSTERS";

export const SET_FILM_ID = "SET_FILM_ID";
export const SET_FILM_NAME = "SET_FILM_NAME";
export const SET_FILM_YEAR = "SET_FILM_YEAR";
export const SET_FILM_DIRECTOR = "SET_FILM_DIRECTOR";
export const SET_FILM_OVERVIEW = "SET_FILM_OVERVIEW";
export const ADD_FILM_RATING = "ADD_FILM_RATING";
export const ADD_FILM_COMMENTS = "ADD_FILM_COMMENTS";
export const ADD_FILM_IMAGES = "ADD_FILM_IMAGES";

export const LOAD_FILM_IMAGES = "LOAD_FILM_IMAGES";
export const LOAD_FILM_COMMENTS = "LOAD_FILM_COMMENTS";
export const LOAD_FILM_RATING = "LOAD_FILM_RATING";
