export const LOADING = "LOADING";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";

export const SET_FILMS_LIST = "SET_FILMS_LIST";
export const SET_POSTERS = "SET_POSTERS";